name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build-master:
    uses: ./.github/workflows/build-master.yml
  deploy:
    needs: build-master
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER_NAME }}
        service_account: ${{ secrets.APPENGINE_DEPLOY_SA_EMAIL }}

    - id: deploy
      uses: google-github-actions/deploy-appengine@v0

    - name: Show output
      run: 'echo ${{ steps.deploy.outputs.url }}'
