# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tune-share-master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # Stop the build if there are lint errors. Uses the configs from setup.cfg
        flake8
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 --exit-zero --max-complexity=10 --max-line-length=127
    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest
